using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class PantallaJuegoJugadorPregunta : MonoBehaviour
{
    int numJugadores, jugadorActualPregunta, jugadorAhoraResponde;
    public Text jugadorPregunta, jugadorResponde, pregunta;

    void Start()
    {
        numJugadores = PlayerPrefs.GetInt("numJugadores");

        jugadorActualPregunta = PlayerPrefs.GetInt("jugadorPregunta");
        jugadorActualPregunta = jugadorActualPregunta + 1;
        if (jugadorActualPregunta == numJugadores + 1) jugadorActualPregunta = 1;
        PlayerPrefs.SetInt("jugadorPregunta", jugadorActualPregunta);
        jugadorPregunta.text = PlayerPrefs.GetString("player"+jugadorActualPregunta);

        jugadorAhoraResponde = jugadorActualPregunta + 1;
        if (jugadorAhoraResponde == numJugadores + 1) jugadorAhoraResponde = 1;
        PlayerPrefs.SetInt("jugadorActual", jugadorAhoraResponde);

        jugadorResponde.text = "Responde " + PlayerPrefs.GetString("player"+ jugadorAhoraResponde);
        ponerPregunta();
        PlayerPrefs.SetString("preguntaActual", pregunta.text);
    }

    public void ponerPregunta()
    {
        int num = Random.Range(1, 201);
        switch (num)
        {
            case 1: pregunta.text = "¿Qué superpoder tendrías?"; break;
            case 2: pregunta.text = "Si pudieras ir a cenar con un personaje histórico, ¿con quién irías?"; break;
            case 3: pregunta.text = "¿Cuál es la mayor locura que querrias cometer en tu vida?"; break;
            case 4: pregunta.text = "¿Cuál es tu palabra favorita?"; break;
            case 5: pregunta.text = "¿A que año te gustaria viajar en el tiempo?"; break;
            case 6: pregunta.text = "¿Qué personaje famoso querrías ser?"; break;
            case 7: pregunta.text = "¿Cómo te describirías en  adjetivos?"; break;
            case 8: pregunta.text = "¿Qué es aquello que no soportas en los demás?"; break;
            case 9: pregunta.text = "¿Cuál es tu refrán favorito?"; break;
            case 10: pregunta.text = "¿Cual es la primera impresión que das? (1 adjetivo)"; break;
            case 11: pregunta.text = "¿Dónde serían tus vacaciones ideales?"; break;
            case 12: pregunta.text = "¿Cuál era tu serie  favorita?"; break;
            case 13: pregunta.text = "¿Qué  cualidades aprecias más en una persona?"; break;
            case 14: pregunta.text = "¿Cuál es el último libro que te has leído?"; break;
            case 15: pregunta.text = "Si pudieras ser un animal, ¿cuál serías?"; break;
            case 16: pregunta.text = "¿Cuál es la parte de tu cuerpo que más te gusta?"; break;
            case 17: pregunta.text = "¿Cuál sería tu eslogan?"; break;
            case 18: pregunta.text = "¿Cuál es el objeto más raro de tu habitación?"; break;
            case 19: pregunta.text = "¿Cuál ha sido la última mentira que has dicho?"; break;
            case 20: pregunta.text = "Si pudieras tener cualquier oficio del mundo, ¿cuál eligirías?"; break;
            case 21: pregunta.text = "¿Cuál es tu tema de conversación favorito?"; break;
            case 22: pregunta.text = "¿Cuál es tu mayor miedo en esta vida?"; break;
            case 23: pregunta.text = "Si pudieras quedarte toda la vida con la misma edad, ¿cuál sería?"; break;
            case 24: pregunta.text = "¿Qué animal te gusta mas"; break;
            case 25: pregunta.text = "¿Cuál es la mejor pregunta que te han hecho o te podrían hacer?"; break;
            case 26: pregunta.text = "¿Qué objeto comprarias para tu habitacion"; break;
            case 27: pregunta.text = "¿A qué personaje histórico te gustaría entrevistar?"; break;
            case 28: pregunta.text = "¿Qué tipo de ropa no llevarías puesta en ningún caso?"; break;
            case 29: pregunta.text = "¿Cuál es tus grupo de música favorito?"; break;
            case 30: pregunta.text = "¿Qué canción serviría para resumir tu personalidad"; break;
            case 31: pregunta.text = "¿Cuál sería un buen título para tu autobiografía?"; break;
            case 32: pregunta.text = "¿A qué le tienes un mayor miedo irracional?"; break;
            case 33: pregunta.text = "¿Cuándo te diste cuenta de que habías madurado"; break;
            case 34: pregunta.text = "¿Que es lo que te da mayor mala suerte"; break;
            case 35: pregunta.text = "Dos famosos con quien harias un trio"; break;
            case 36: pregunta.text = "¿De qué te disfrazarías como fantasía sexual?"; break;
            case 37: pregunta.text = "Lugar mas raro donde te gustaria hacerlo"; break;
            case 38: pregunta.text = "Última persona a la que hice llorar"; break;
            case 39: pregunta.text = "Nombre de la ultima peli porno que he visto"; break;
            case 40: pregunta.text = "¿Cuántos días seguidos estuve sin ducharme?"; break;
            case 41: pregunta.text = "¿Cuál es el pensamiento más sucio que has tenido sobre un completo desconocido?"; break;
            case 42: pregunta.text = "¿Qué es lo más extraño que has pensado al tocarte a ti mismo"; break;
            case 43: pregunta.text = "Género del porno mas raro que he visto"; break;
            case 44: pregunta.text = "¿Cuál es la cosa más rara que te excita?"; break;
            case 45: pregunta.text = "¿Qué es lo más arriesgado que has hecho por amor?"; break;
            case 46: pregunta.text = "¿Cuál es la mayor locura que has hecho en tu vida?"; break;
            case 47: pregunta.text = "Si tuvieras una lámpara mágica y el genio te concediera un deseo, ¿cuál sería?"; break;
            case 48: pregunta.text = "¿Qué es lo más raro que has comido?"; break;
            case 49: pregunta.text = "¿Cuál consideras que es tu mejor habilidad?"; break;
            case 50: pregunta.text = "¿Qué es lo más vergonzoso que has hecho?"; break;
            case 51: pregunta.text = "¿A qué persona tienes que pedir perdón?"; break;
            case 52: pregunta.text = "¿Cuál es tu comida favorita?"; break;
            case 53: pregunta.text = "Perdonarías una infidelidad a cambio de..."; break;
            case 54: pregunta.text = "Asi es como quiero morir"; break;
            case 55: pregunta.text = "Una cena romantica no estaria completa sin..."; break;
            case 56: pregunta.text = "Antes de matarte quiero que me enseñes..."; break;
            case 57: pregunta.text = "Has hecho llorar a esa persona, ¿qué le has hecho?"; break;
            case 58: pregunta.text = "Durante el sexo me gusta pensar en..."; break;
            case 59: pregunta.text = "Tengo muchos problemas pero.... no es uno de ellos"; break;
            case 60: pregunta.text = "Lo siento profesor, no pude terminar los deberes porque..."; break;
            case 61: pregunta.text = "Si yo fuera un superheroe, mi nombre seria..."; break;
            case 62: pregunta.text = "Mi vida cambió cuando me enseñaron..."; break;
            case 63: pregunta.text = "Acabo de apuntarme a un campeonato mundial de..."; break;
            case 64: pregunta.text = "Vengo de ver una exposición de..."; break;
            case 65: pregunta.text = "Pienso que el mundo se va a acabar por culpa de..."; break;
            case 66: pregunta.text = "He tenido un hijo y creo que es..."; break;
            case 67: pregunta.text = "Mi madre me acaba de llamar y me ha dicho que..."; break;
            case 68: pregunta.text = "Este verano he ido a Japón y he comprado..."; break;
            case 69: pregunta.text = "Acabo de darle una hostia a una anciana, no tolero que..."; break;
            case 70: pregunta.text = "He discutido con un policia, me ha dicho que.."; break;
            case 71: pregunta.text = "Mi última relación acabó por culpa de..."; break;
            case 72: pregunta.text = "¿Que es lo que nunca me falla para tener sexo?"; break;
            case 73: pregunta.text = "¿Cual es mi vicio secreto?"; break;
            case 74: pregunta.text = "¿Qué llevaría al pasado para convencer a la gente que soy un mago poderoso?"; break;
            case 75: pregunta.text = "¿Cual es mi poder secreto?"; break;
            case 76: pregunta.text = "¿A que huelo?"; break;
            case 77: pregunta.text = "Mi voz se parece a..."; break;
            case 78: pregunta.text = "Si me chuparas un dedo, ¿a qué sabría?"; break;
            case 79: pregunta.text = "¿Qué pondría yo de nuevo juguete en el Happy Meal?"; break;
            case 80: pregunta.text = "Voy a construir una estatua de...	"; break;
            case 81: pregunta.text = "Cuando sea presidente voy a crear el Ministerio de..."; break;
            case 82: pregunta.text = "Tengo pesadillas con..."; break;
            case 83: pregunta.text = "¿Cuál es tu bebida favorita?"; break;
            case 84: pregunta.text = "¿Cuál ha sido tu mayor logro?	"; break;
            case 85: pregunta.text = "¿Cuál es la pelicula que más odias?"; break;
            case 86: pregunta.text = "He dejado el trabado, no me gustaba seguir trabajando de..."; break;
            case 87: pregunta.text = "¿Cuál es tu próxima meta?	"; break;
            case 88: pregunta.text = "¿Cuál es tu web favorita?	"; break;
            case 89: pregunta.text = "¿Qué es lo más impresionante que sabes hacer?"; break;
            case 90: pregunta.text = "Si la vida fuera un juego ¿Cómo se llamaria?"; break;
            case 91: pregunta.text = "Voy a crear una ONG y se va a llamar..."; break;
            case 92: pregunta.text = "¿Cuál es el peor regalo que te han hecho?"; break;
            case 93: pregunta.text = "¿Cuál es el título del capítulo actual de tu vida?"; break;
            case 94: pregunta.text = "¿Cómo te gustaría ser recordado?"; break;
            case 95: pregunta.text = "¿Cuál es una de las responsabilidades que jamás quisieras tener?"; break;
            case 96: pregunta.text = "Si tu infancia tuviera olor ¿Cuál sería?"; break;
            case 97: pregunta.text = "¿Cuál es una  de tus reglas personales que jamás rompes?"; break;
            case 98: pregunta.text = "Si pudieras tener un vídeo de cualquier evento de tu vida ¿Cuál sería?"; break;
            case 99: pregunta.text = "Cual fue la decision mas importante de tu vida"; break;
            case 100: pregunta.text = "¿Qué te quita el sueño?"; break;
            case 101: pregunta.text = "¿Cuál es la mentira que dices más a menudo?"; break;
            case 102: pregunta.text = "¿Qué temes que la gente note cunado te mira?"; break;
            case 103: pregunta.text = "¿Qué piensas de la sociedad actual?"; break;
            case 104: pregunta.text = "¿Quién es tu amor platónico?"; break;
            case 105: pregunta.text = "¿Cuál es tu mayor fobia?"; break;
            case 106: pregunta.text = "¿Qué es lo más difícil que has hecho en la vida?"; break;
            case 107: pregunta.text = "¿Cual es tu mayor remordimiento en la vida?"; break;
            case 108: pregunta.text = "¿Cuál es la travesura más divertida que has hecho en tu vida?"; break;
            case 109: pregunta.text = "Voy a llamar a mi hijo..."; break;
            case 110: pregunta.text = "¿Qué es lo más raro que has visto en tu vida?"; break;
            case 111: pregunta.text = "¿Cuál es el trabajo más raro que estarías dispuesto a hacer?"; break;
            case 112: pregunta.text = "¿Si pudieras vivir dentro de una película cuál sería?"; break;
            case 113: pregunta.text = "¿Cuál es tu técnica de seducción más infalible?"; break;
            case 114: pregunta.text = "¿Cómo intentarías seducirme?	"; break;
            case 115: pregunta.text = "Si pudiera hablar con mi yo del futuro ¿Qué le preguntarías?"; break;
            case 116: pregunta.text = "¿Que apodo me pondrias?"; break;
            case 117: pregunta.text = "¿Qué harías si conocieras a tu doble?"; break;
            case 118: pregunta.text = "¿Cuál es tu combinación más rara de comida?"; break;
            case 119: pregunta.text = "Si te llegara a arrestar la policía ¿Cuál creerías que es el motivo?"; break;
            case 120: pregunta.text = "Si tuvieras que conquistarme solo con una frase ¿Qué frase usarías?"; break;
            case 121: pregunta.text = "Si tuvieras un Guinnes Record ¿En qué sería?	"; break;
            case 122: pregunta.text = "¿Cuál es la palabra más graciosa?"; break;
            case 123: pregunta.text = "¿Qué es lo más agradable que he visto en internet?"; break;
            case 124: pregunta.text = "¿Qué es lo más desagradable que has visto en internet?"; break;
            case 125: pregunta.text = "Si tuvieras que ponerte un nombre a ti mismo ¿Cuál elegirías?"; break;
            case 126: pregunta.text = "¿En caso de que hubiera un apocalipsis zombie cuál sería tu actitud?"; break;
            case 127: pregunta.text = "¿Cuál es ese sueño que nunca le has contado a nadie?	"; break;
            case 128: pregunta.text = "¿Qué es lo más vergonzoso que podría encontrar en tu historial de navegación?"; break;
            case 129: pregunta.text = "Si pudieras dedicarte a hacer cualquier cosa y que por ello te paguen ¿Qué elegirías?"; break;
            case 130: pregunta.text = "¿Cuál fue el mejor cumpleaños que tuviste?"; break;
            case 131: pregunta.text = "¡Te ves genial! ¿Cuál es tu rutina de ejercicios?"; break;
            case 132: pregunta.text = "Me arrepiento de haber hecho aquella broma, consistía en..."; break;
            case 133: pregunta.text = "Defíneme en  insultos"; break;
            case 134: pregunta.text = " Si tu vida fuera una telenovela, ¿cómo se llamaría?"; break;
            case 135: pregunta.text = " Si tuvieran que torturarte con una canción, ¿con cuál sería?"; break;
            case 136: pregunta.text = "¿Qué te gustaría que escribieran en tu esquela?"; break;
            case 137: pregunta.text = "¿Qué dibujo animado serías?"; break;
            case 138: pregunta.text = "Mi habilidad absurda consiste en..."; break;
            case 139: pregunta.text = "Ojalá mis pedos olieran a..."; break;
            case 140: pregunta.text = "Me lo merezco, acaban de darme una hostia por..."; break;
            case 141: pregunta.text = "¿Cuál sería el dato sobre ti más ridículo o vergonzoso?"; break;
            case 142: pregunta.text = "Ponme un mote"; break;
            case 143: pregunta.text = "si tuviera que crear una secta, adoraríamos a..."; break;
            case 144: pregunta.text = "Mi vida se resumen en.."; break;
            case 145: pregunta.text = "¿Cuál es la palabra a la que le tienes más manía?"; break;
            case 146: pregunta.text = "¿Cuál es la comida más rara que has preparado o probado?"; break;
            case 147: pregunta.text = "¿Cuál es el sitio más raro en el que has evacuado?"; break;
            case 148: pregunta.text = "Si tuvieran que torturarte con algo que para otros es un placer, ¿cuál sería esa tortura?"; break;
            case 149: pregunta.text = "Si tienes 100 unidades de un producto que no puedes vender o consumir, ¿cuál sería?"; break;
            case 150: pregunta.text = "¿Qué moda actual te parece más ridícula?"; break;
            case 151: pregunta.text = "Si fueras el dueño de un parque temático, ¿cuál sería la temática del parque?"; break;
            case 152: pregunta.text = "¿Qué animal fantástico te gustaría que existiera?"; break;
            case 153: pregunta.text = "¿Cuál es el sueño más raro que has tenido nunca?"; break;
            case 154: pregunta.text = "¿Qué crees que podría ser considerado un nuevo deporte?"; break;
            case 155: pregunta.text = "¿Qué actor te interpretaría si hicieran una película sobre ti?"; break;
            case 156: pregunta.text = "Si solo pudieras comer un plato el resto de tu vida, ¿cuál sería?"; break;
            case 157: pregunta.text = "Si al morir te incineraran y tuvieran que esparcir tus cenizas en algún lugar extraño, ¿cuál sería?"; break;
            case 158: pregunta.text = "Con quien te intercambiarias el cuerpo durante un dia"; break;
            case 159: pregunta.text = "Que superpoder inservible tendria?"; break;
            case 160: pregunta.text = "Te despiertas de repente en medio de la noche. ¿Cuál sería el sonido que te resultaría mas aterrador escuchar al despertar?"; break;
            case 161: pregunta.text = "¿En qué trabajo exigente y difícil crees que podrías fingir tener mucha experiencia y que nadie se diera cuenta?"; break;
            case 162: pregunta.text = "¿Quien es tu mayor enemigo? (persona)"; break;
            case 163: pregunta.text = "¿Qué cosa infantil todavía disfrutas haciendo?"; break;
            case 164: pregunta.text = "¿Qué película puedes ver una y otra vez sin cansarte?"; break;
            case 165: pregunta.text = "¿Cuál es el dato curioso más interesante que conoces?"; break;
            case 166: pregunta.text = "¿Cuál es la cosa más inútil que sabes hacer?	"; break;
            case 167: pregunta.text = "¿Qué cosas estás cansado de escuchar?"; break;
            case 168: pregunta.text = "¿Cuál es la mayor duda que tienes?"; break;
            case 169: pregunta.text = "¿Qué NO harías por  millon de euros?	"; break;
            case 170: pregunta.text = "¿Cuál es el peor recuerdo que tienes?"; break;
            case 171: pregunta.text = "Si tuvieras que elegir una causa a la cual dedicar tu vida, ¿qué causa sería?"; break;
            case 172: pregunta.text = "Si murieras hoy, ¿cuál sería tu mayor logro hasta la fecha?"; break;
            case 173: pregunta.text = "Para hacer del mundo un lugar mejor, he hecho...	"; break;
            case 174: pregunta.text = "¿Cuál ha sido la peor compra que has hecho en tu vida?"; break;
            case 175: pregunta.text = "¿Qué comida te parece más desagradable?"; break;
            case 176: pregunta.text = "¿Qué debe pasar en una película para que te levantes y te vayas del cine?"; break;
            case 177: pregunta.text = "¿Sobre qué cosa podrías dar una conferencia improvisada de dos horas?"; break;
            case 178: pregunta.text = "¿En qué dos cosas nunca te gastarías dinero?	"; break;
            case 179: pregunta.text = "¿Cual es tu villano de ficción favorito?	"; break;
            case 180: pregunta.text = "¿En que juego siempre pierdes?"; break;
            case 181: pregunta.text = "¿Qué te gusta hacer que tradicionalmente se considere del sexo contrario?"; break;
            case 182: pregunta.text = "¿Qué es lo más raro que solías comer de niño?"; break;
            case 183: pregunta.text = "¿Cuál fue la última película que te hizo llorar?	"; break;
            case 184: pregunta.text = "¿Hay algo que creas que todos deberían experimentar al menos una vez en su vida?	"; break;
            case 185: pregunta.text = "¿Cual crees que sería el peor famoso para tener una cena con el?	"; break;
            case 186: pregunta.text = "¿Tienes alguna combinación de sabores que sea rara pero que te guste?"; break;
            case 187: pregunta.text = "¿Cuál ha sido la mejor forma en la que gastaste 5€?	"; break;
            case 188: pregunta.text = "¿Qué es lo peor que has probado en tu vida?"; break;
            case 189: pregunta.text = "Voy a empezar una colección de..."; break;
            case 190: pregunta.text = "Mis padres me han ocultado..."; break;
            case 191: pregunta.text = "Estoy escribiendo un libro sobre mi vida, se titula..."; break;
            case 192: pregunta.text = "Mi sonido favorito es...	"; break;
            case 193: pregunta.text = "Me excito bastante cuando oigo..."; break;
            case 194: pregunta.text = "Me excito bastante siempre que pienso en..."; break;
            case 195: pregunta.text = "Me he dado cuenta de que...	"; break;
            case 196: pregunta.text = "Odio cuando, en Internet, me salen banners publicitando..."; break;
            case 197: pregunta.text = "He creado un videojuego, el protagonista es..."; break;
            case 198: pregunta.text = "Soy el mayor experto en..."; break;
            case 199: pregunta.text = "Tengo hambre, ojalá comerme ahora.."; break;
            case 200: pregunta.text = "Voy a vomitar, me ha sentado mal, lo de..."; break;
        }
    }
}
